chore: change deps commit type from fix to chore
kintone/cli-kintone pull request #821
Opened 2024-07-23 00:29 UTC by shabaraba

## Why

The commit type for updating deps is fix, but we don't want to do this because it shows up as Bug Fixes in the release notes.

## What

Change the commit type from `fix` to `chore`.

## Checklist

- [x] Read [CONTRIBUTING.md](https://github.com/kintone/cli-kintone/blob/main/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added/updated tests if it is required. (or tested manually)
- [x] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-07-25 10:23 UTC, tasshi-me requested changes

2024-07-25 10:23 UTC, tasshi-me commented on renovate.json5
> +          "devDependencies"
cybozu/renovate-configの設定ですが、
1. 全てのパッケージでcommitTypeを`chore`にして([ref](https://github.com/cybozu/renovate-config/blob/373ca1ae78f7d668cc8a767d915cab5e19f45438/default.json#L30))
2. `deps`, `peerDeps`だけはcommitTypeを`fix`にしてます([ref](https://github.com/cybozu/renovate-config/blob/373ca1ae78f7d668cc8a767d915cab5e19f45438/default.json#L36))

なので、設定としては
- `deps` => `fix`
- `devDeps` => `chore`
- `peerDeps` => `fix`

となっていて、このファイルで上書きしないといけないのは`deps`, `peerDeps`になります!

ただし、元の設定に依存せずに全て`chore`にするほうが安全なので、ここでは`matchDepTypes`の指定を消すと良さそうです。

2024-07-26 02:42 UTC, shabaraba commented on renovate.json5
> +          "devDependencies"
全然読めてませんでした...ありがとうございます
[6d4e07a](https://github.com/kintone/cli-kintone/pull/821/commits/6d4e07a31f4f971a1490eaf782c435e6c74804ab)で対応しました

2024-07-26 06:06 UTC, tasshi-me approved these changes

2024-07-26 06:07 UTC, merged