chore: plugin pack command for 2
kintone/cli-kintone pull request #916
Opened 2024-10-24 20:20 UTC by tasshi-me

## Why

## What

## How to test

## Checklist

- [ ] Read [CONTRIBUTING.md](https://github.com/kintone/cli-kintone/blob/main/CONTRIBUTING.md)
- [ ] Updated documentation if it is required.
- [ ] Added/updated tests if it is required. (or tested manually)
- [ ] Passed `pnpm lint` and `pnpm test` on the root directory.

2024-10-25 05:28 UTC, tasshi-me commented
前のPRでレビュー持ったところ
- https://github.com/kintone/cli-kintone/pull/915/files#r1815855917
- https://github.com/kintone/cli-kintone/pull/915/files#r1815859115

2024-10-28 16:53 UTC, tasshi-me reviewed
補足コメント書きました。
かなり大胆にリファクタしたので、↓の概念図も参考にしてください！ 🙏 

![image](https://github.com/user-attachments/assets/330db9f9-11e4-4388-8350-b3cf69b21cf2)

2024-10-28 16:53 UTC, tasshi-me commented on package.json
> -    "stream-buffers": "^3.0.3",
`stream-buffers`は Node.js 標準の [Utility Consumers](https://nodejs.org/dist/latest-v16.x/docs/api/webstreams.html#utility-consumers) に置き換えが案内されていたので置き換えた。
https://www.npmjs.com/package/stream-buffers

2024-10-28 16:53 UTC, tasshi-me commented on package.json
> -    "debug": "^4.3.7",
`debug` はcli-kintoneの`logger.debug|trace`に置き換えた。

2024-10-28 16:53 UTC, tasshi-me commented on package.json
> -    "mkdirp": "^3.0.1",
`fs.promises.mkdir(data, {recursive: true})` に置き換え

2024-10-28 16:53 UTC, tasshi-me commented on package.json
> -    "execa": "^9.4.1",
使用していたテストを消した。

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/core/crypto/index.ts
> +export type { PrivateKeyInterface } from "./private-key";
PublicKey と PrivateKey は変わることは当面なさそうだしInterfaceを切らなくても良さそう。
（アルゴリズムなどが変わるタイミングでIFを切れば良さそう）

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/core/driver/interface.ts
> +  statSync(fileName: string): FileStats;
`plugin-manifest-validator`が非同期に未対応のため、同期関数が必要。

2024-10-28 16:53 UTC, tasshi-me commented on src/cli/plugin/info.ts
> +const command = "info";
`info`コマンドはプラグインファイルの情報を表示するコマンド。

設計で本当にpack以外のコマンドが実装しやすくなっているかの検証も兼ねて実装

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/core/index.ts
> +export { PluginZip } from "./plugin";
個別のコマンドに依存しない、プラグインに関する汎用的な操作はcoreモジュールに移動した。

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/packer/__tests__/cli.test.ts
> -describe("cli", () => {
この試験に色々なレイヤーの試験が全部入っていたので、各モジュールごとに切り分けた。

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/packer/__tests__/helpers/zip.ts
> -export const readZipContentsNames = (
`ZipFileDriver.fileList()`で置き換えられたため削除。

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/packer/console.ts
> -export = {
cli-kintoneの`logger`に置き換えた

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/packer/gen-error-msg.ts
> -export const generateErrorMessages = (errors: Ajv.ErrorObject[]): string[] => {
`manifest/validate`に移動

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/packer/create-contents-zip.ts
> -export const createContentsZip = (
`contents/zip`に移動

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/packer/index.ts
> -const packer = (
packerの処理は`PluginZip.build()`に移動した。

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/packer/pack-plugin-from-manifest.ts
> -export const packPluginFromManifest = (
こちらも`PluginZip.build()`に集約

2024-10-28 16:53 UTC, tasshi-me commented on website/docs/guide/commands/plugin-info.md
> +draft: true
`draft: true`なのでローカルビルドでした表示されない

2024-10-28 16:53 UTC, tasshi-me commented on src/cli/stability.ts
> +export const setStability = <T = {}, U = {}>(
https://github.com/kintone/cli-kintone/pull/915/files#r1815855917 の対応

`setStability(cmd, stability, msg)` 関数を追加した。
ヘルプメッセージにStabilityが表示され、実行時に警告が出るようになる。

---
どこかのflagsにstabilityの情報を集約して、それに連動して表示が変わるようにしたかったが、yargsの仕組み上難しそうだった。

コマンドの生成を全てラップするヘルパー関数を置けば実現できるが、既存のレコード系のコマンドにも影響が出るので今回は個別のコマンドをラップする方式にした。

2024-10-28 16:53 UTC, tasshi-me commented on src/plugin/packer/cli.ts
> +export const run = async (pluginDir: string, options_?: Options) => {
既存のレコード系のコマンドと合わせて関数名を `run` にした。

ref. https://github.com/kintone/cli-kintone/pull/915/files#r1815859115

2024-10-30 05:25 UTC, shabaraba requested changes
@tasshi-me 
いくつかコメントしました！
定義がわかりやすくて処理が追いやすかったです！

2024-10-30 05:25 UTC, shabaraba commented on src/plugin/core/manifest/interface.ts
> +  validate(driver?: DriverInterface): Promise<ValidationResult>;
![Static Badge](https://img.shields.io/badge/review-imo-blue)
- `ManifestStaticInterface.loadJsonFile`でdriverを渡している
- `ManifestInterface`のメソッドでも`driver`をしばしば引数で取る

ので、`ManifestInterface`のプロパティに入れてしまってもいいんじゃないかなと思ったのですがいかがでしょう？

もしくは、driverをメソッドごとに使い分けるユースケースが何かイメージありますでしょうか？

2024-10-30 05:25 UTC, shabaraba commented on src/plugin/core/contents/zip.ts
> +export const _createContentsZipStream = async (
![Static Badge](https://img.shields.io/badge/review-q-orange)
こちらのメソッドは未使用のようですが、`createContentsZip`と比較するために用意している、という理解で良いでしょうか？
（あと今後もし使用するのであれば、exportしているのにアンダースコアから始まるのが少し気になりました）

2024-10-30 05:25 UTC, shabaraba commented on src/plugin/core/plugin/index.ts
> +  public static async buildFromContentsZip(
![Static Badge](https://img.shields.io/badge/review-nits-green)
`contentsZip`では`createXxx`というメソッド名だったので、どちらかの命名に統一できると良さそうに思いました。

またcontentsの方は`zip.ts`が切り出されているので、構造が（似せれるなら）似ているとよりわかりやすいかなと思いました。

2024-10-30 05:25 UTC, shabaraba commented on src/plugin/packer/cli.ts
> +export const run = async (pluginDir: string, options_?: Options) => {
![Static Badge](https://img.shields.io/badge/review-nits-green)
めちゃ細かいんですが、ファイル名も（`pack.ts`とか？）機能に則したものの方が良さそうに思いました。

2024-10-30 05:25 UTC, shabaraba commented on src/plugin/packer/cli.ts
> +  logger.debug(`id: ${id}`);
![Static Badge](https://img.shields.io/badge/review-nits-green)
処理の順番に意味がもしなければ、`// 7. package plugin.zip`で再びこのあたりで定義した変数を利用するので、
` // 6. prepare output directory`の後ろにこの処理群を持っていったほうが良さそうに思いましたがいかがでしょうか？

2024-11-01 09:36 UTC, tasshi-me commented on src/plugin/packer/cli.ts
> +  logger.debug(`id: ${id}`);
あざます！
処理順番を調整しました。

1. 入力のバリデーション
2. マニフェストの読み込み
3. マニフェストの検証
4. 出力ディレクトリの用意
5. 秘密鍵の読み込み、指定されていない場合は生成
6. プラグインのパッケージング
7. watchモードの起動（指定されている場合）
8. プラグインの書き出し

2024-11-01 09:51 UTC, tasshi-me commented on src/plugin/packer/cli.ts
> +export const run = async (pluginDir: string, options_?: Options) => {
pack.tsにしました！

2024-11-01 09:51 UTC, tasshi-me commented on src/plugin/core/plugin/index.ts
> +  public static async buildFromContentsZip(
`build`/`generate`/`create`が散らばっているんですが、一旦全て`generate`/`generateFrom`に統一しました。

2024-11-02 08:41 UTC, tasshi-me commented on src/plugin/core/contents/zip.ts
> +export const _createContentsZipStream = async (
Streamを使ったほうが速度的にもメモリ使用量的にも良さそうなんですけど、まだあまりちゃんと検証していないので置き換えずに置いているような状態です！
一旦はExportしない状態にしました！

2024-11-02 09:20 UTC, tasshi-me commented on src/plugin/core/manifest/interface.ts
> +  validate(driver?: DriverInterface): Promise<ValidationResult>;
@shabaraba 
これも悩んでいた部分ですね！
ManifestがDriverに依存しなくても成立する概念なので、Driverをプロパティに含めていませんでした！

直近は、
・マニフェストを読み込む場所
・マニフェストからファイルの実在を検証する場所
は一緒なので、プロパティに入れてしまっても問題ないと思います。

一方で、今後Driverを使い分けるケースとしては、以下のようなケースを想定しています。
・ZIPファイルやHTTPをソースとして受け付けてローカルにプラグインを生成するパターン
・Webエディタのようなオンメモリ→ZIPファイルを生成するパターン
・Web版plugin-packerのように入力ZIPファイルからプラグインZIPファイルを生成するパターン
　（ZipFileDriverは1つのZIPファイル内のファイル構造を表現しているので、入力・出力で2つのZIPファイルを扱う場合はDriverは2つ必要になります）

---
自分の考えなのですが、
・`ManifestInterface.validate()`はManifestの形式的な妥当性だけを検証する
・Driverを使ったファイルの実在確認は`Contents.validate()`を作成する
・ContentsはDriverに依存する（コンストラクタインジェクションする）
とすると見通しが良くなりそうです。

2024-11-02 09:24 UTC, tasshi-me commented on src/plugin/core/manifest/interface.ts
> +  validate(driver?: DriverInterface): Promise<ValidationResult>;
(なんだかんだ言ってメインの利用ケースはfsなので、デフォルト引数をfsにしておいても良さそう)

2024-11-02 10:06 UTC, tasshi-me reviewed
レビュー対応

2024-11-02 10:08 UTC, tasshi-me commented on src/plugin/core/plugin/index.ts
> +  public static async buildFromContentsZip(
`zip.ts`の切り出しも行いました！

2024-11-05 06:58 UTC, tasshi-me commented on src/plugin/core/manifest/interface.ts
> +  validate(driver?: DriverInterface): Promise<ValidationResult>;
ContentsがManifestとDriverに依存する、という構成でリファクタすることにしたが、一旦保留とした。
現在plugin-manifest-validatorに任せている処理を移植する必要があり、コストがそこそこありそうなため。
TODOコメントを残した。

2024-11-06 01:02 UTC, shabaraba approved these changes
ご対応ありがとうございました！良さそうです！

2024-11-06 01:18 UTC, merged